import { describe, it, expect } from 'vitest'
import { formatTypeScript } from '../../src/writer/format'

describe('formatTypeScript', () => {
  it('rewrites hand-rolled object literals into prettier layout', async () => {
    // What the printer would emit for an apiDefinitions body: dense one-liner.
    const input = `export default {
  'User.get': ['GET', '/user'],
  'User.create': ['POST', '/user']
};
`
    const out = await formatTypeScript(input)
    expect(out).toMatchInlineSnapshot(`
      "export default {
        'User.get': ['GET', '/user'],
        'User.create': ['POST', '/user'],
      }
      "
    `)
  })

  it('honors project prettier config (no trailing semicolons, single quotes)', async () => {
    const out = await formatTypeScript(`const a="x";\nconst b="y";\n`)
    expect(out).not.toMatch(/;\n/)
    expect(out).toContain("'x'")
    expect(out).toContain("'y'")
  })

  it('handles TS-only syntax (declare global, generics)', async () => {
    const input = `declare global { interface Foo<T> { bar: T } }\nexport {};\n`
    const out = await formatTypeScript(input)
    expect(out).toContain('declare global')
    expect(out).toContain('Foo<T>')
    expect(out).toContain('export {}')
  })

  it('leaves string literal contents untouched (escapes, comments)', async () => {
    const input = `export const msg = "hello \\\"world\\\" /\\\\/ end"\n`
    const out = await formatTypeScript(input)
    expect(out).toContain('\'hello "world" /\\\\/ end\'')
  })

  it('preserves leading docblock comments above declarations', async () => {
    const input = `/** generated by openapi-generator */\nexport const x = 1\n`
    const out = await formatTypeScript(input)
    expect(out).toContain('/** generated by openapi-generator */')
    expect(out).toContain('export const x = 1')
  })

  it('returns input unchanged when source is empty or whitespace-only', async () => {
    expect(await formatTypeScript('')).toBe('')
    expect(await formatTypeScript('\n\n  \n')).toBe('\n\n  \n')
  })

  it('propagates prettier errors so callers can decide whether to fall back', async () => {
    // Missing comma → TS parser rejects → formatTypeScript must throw
    // rather than swallow; "skip + warn" lives in generate(), not here.
    const broken = `const x = {\n  a: 1\n  b: 2\n`
    await expect(formatTypeScript(broken)).rejects.toThrow()
  })
})
