/**
 * Wormhole-equivalent header section for globals.d.ts.
 *
 * Mirrors src/templates/globals.d.handlebars from
 * https://github.com/alovajs/devtools/tree/main/packages/wormhole.
 *
 * Differences from the simple "Generated by openapi-generator" header:
 *   - Imports use `typeof import('./index')['alovaInstance']` so the
 *     Alova2MethodConfig/Alova2Method generics are inferred from the actual
 *     alova instance the user creates, not from the abstract `Alova` symbol
 *     (the latter collapses to `any` once Alova uses AlovaGenerics).
 *   - Alova2MethodConfig / Alova2Method / ExtractUserDefinedTransformed match
 *     the wormhole template verbatim; collapsing these three into a single
 *     block keeps the generator output valid for both alova v2 and v3.
 */
export const IMPORTS = [
  "import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';",
  "import type { $$userConfigMap, alovaInstance } from './index';",
  "import type apiDefinitions from './apiDefinitions';",
].join('\n')

export const HEADER_TYPES = `type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;`
