/**
 * Leading docblock shared by apiDefinitions.ts / createApis.ts / globals.d.ts.
 *
 * Centralized here so the three generated files can never drift. Callers pass
 * the {title, version, openapiVersion} metadata read from the OpenAPI doc.
 */
export interface HeaderMeta {
  title: string
  version: string
  openapiVersion: string
}

export function renderHeaderComment(meta: HeaderMeta): string {
  return [
    '/* tslint:disable */',
    '/* eslint-disable */',
    '/**',
    ` * ${meta.title} - version ${meta.version}`,
    ' *',
    ` * OpenAPI version: ${meta.openapiVersion}`,
    ' *',
    ' *',
    ' * NOTE: This file is auto generated by the openapi-generator.',
    ' *',
    ' * https://github.com/seepine/openapi-generator',
    ' *',
    ' * **Do not edit the file manually**',
    ' * **该文件由工具自动生成，请勿手动修改**',
    ' *',
    ' */',
  ].join('\n')
}
